### Texture Analysis Project

Aim to read data from multiple excel files in a folder tree and to correlate in a single dataframe

In [1]:
import os
import csv
import pandas as pd

In [2]:
# Create empty lists to store file paths
file_paths_201401 = []
file_paths_201901 = []

# Loop through Data folder in project folder
for root, dirs, files in os.walk(r'C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data'):
    for file in files:
        if '.csv' in file:
            if root.endswith('2014 Trips'):
                print(file)
                path = os.path.join(root, file)
                print(path)
                file_paths_201401.append(path)
                
            if root.endswith('2019 Trips'):
                print(file)
                path = os.path.join(root, file)
                print(path)
                file_paths_201901.append(path)

2014-01 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-01 - Citi Bike trip data.csv
2014-02 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-02 - Citi Bike trip data.csv
2014-03 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-03 - Citi Bike trip data.csv
2014-04 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-04 - Citi Bike trip data.csv
2014-05 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-05 - Citi Bike trip data.csv
2014-07 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-07 - Citi Bike trip data.csv
2014-08 - Citi Bike trip data.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\2014-08 - Citi Bike trip data.csv
201409-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\201409-citibike-tripdata.csv
201410-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\201410-citibike-tripdata.csv
201411-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\201411-citibike-tripdata.csv
201412-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2014 Trips\201412-citibike-tripdata.csv
201901-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201901-citibike-tripdata.csv
201902-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201902-citibike-tripdata.csv
201903-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201903-citibike-tripdata.csv
201904-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201904-citibike-tripdata.csv
201905-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201905-citibike-tripdata.csv
201906-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201906-citibike-tripdata.csv
201907-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201907-citibike-tripdata.csv
201908-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201908-citibike-tripdata.csv
201909-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201909-citibike-tripdata.csv
201910-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201910-citibike-tripdata.csv
201911-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201911-citibike-tripdata.csv
201912-citibike-tripdata.csv
C:\Users\alever\Desktop\Data Analytics Homework\Tableau\Data\2019 Trips\201912-citibike-tripdata.csv

In [3]:
print(file_paths_201401)
print(file_paths_201901)

['C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-01 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-02 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-03 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-04 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-05 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-07 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\2014-08 - Citi Bike trip data.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\201409-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\201410-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\201411-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2014 Trips\\201412-citibike-tripdata.csv']
['C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201901-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201902-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201903-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201904-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201905-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201906-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201907-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201908-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201909-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201910-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201911-citibike-tripdata.csv', 'C:\\Users\\alever\\Desktop\\Data Analytics Homework\\Tableau\\Data\\2019 Trips\\201912-citibike-tripdata.csv']

In [4]:
# Create emptry dataframes to store 2014 data from .csv files
df201401 = pd.DataFrame()
df201901 = pd.DataFrame()

for f in file_paths_201401:
    df = pd.read_csv(f)
    df201401 = df201401.append(df,ignore_index=True)

# Save Dataframe to .csv
df201401.to_csv("2014_Trips.csv")

# Show dataframe
df201401

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009,Catherine St & Monroe St,40.711174,-73.996826,263,Elizabeth St & Hester St,40.717290,-73.996375,16379,Subscriber,1986,1
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536,1 Ave & E 30 St,40.741444,-73.975361,259,South St & Whitehall St,40.701221,-74.012342,15611,Subscriber,1963,1
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228,E 48 St & 3 Ave,40.754601,-73.971879,2022,E 59 St & Sutton Pl,40.758491,-73.959206,16613,Subscriber,1991,1
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519,Pershing Square N,40.751884,-73.977702,526,E 33 St & 5 Ave,40.747659,-73.984907,15938,Subscriber,1989,1
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436,Hancock St & Bedford Ave,40.682166,-73.953990,19830,Subscriber,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7144331,553,12/31/2014 23:55:22,1/1/2015 00:04:35,82,St James Pl & Pearl St,40.711174,-74.000165,2008,Little West St & 1 Pl,40.705693,-74.016777,16908,Subscriber,1982,1
7144332,1355,12/31/2014 23:56:37,1/1/2015 00:19:12,325,E 19 St & 3 Ave,40.736245,-73.984738,327,Vesey Pl & River Terrace,40.715338,-74.016584,20964,Subscriber,1971,1
7144333,431,12/31/2014 23:57:03,1/1/2015 00:04:14,536,1 Ave & E 30 St,40.741444,-73.975361,491,E 24 St & Park Ave S,40.740964,-73.986022,20845,Subscriber,1963,1
7144334,332,12/31/2014 23:57:25,1/1/2015 00:02:57,293,Lafayette St & E 8 St,40.730287,-73.990765,317,E 6 St & Avenue B,40.724537,-73.981854,15374,Subscriber,1984,1
7144335,2048,12/31/2014 23:58:16,1/1/2015 00:32:24,440,E 45 St & 3 Ave,40.752554,-73.972826,264,Maiden Ln & Pearl St,40.707065,-74.007319,20831,Subscriber,1984,1

In [5]:
# Create emptry dataframes to store 2014 data from .csv files
df201901 = pd.DataFrame()

for f in file_paths_201901:
    df = pd.read_csv(f)
    df201901 = df201901.append(df,ignore_index=True)

# Save Dataframe to .csv
df201901.to_csv("2019_Trips.csv")

# Show dataframe
df201901

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20551692,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,2
20551693,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,1
20551694,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672816,-73.983524,27746,Subscriber,1935,2
20551695,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,1
20551696,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,0

In [6]:
# Concatanate the 2014 and 2019 dataframes
Trips20142019 = pd.concat([df201401, df201901])

# Save Dataframe to .csv
Trips20142019.to_csv("Trips20142019.csv")

# Show new dataframe
Trips20142019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,471,2014-01-01 00:00:06,2014-01-01 00:07:57,2009.0,Catherine St & Monroe St,40.711174,-73.996826,263.0,Elizabeth St & Hester St,40.717290,-73.996375,16379,Subscriber,1986,1
1,1494,2014-01-01 00:00:38,2014-01-01 00:25:32,536.0,1 Ave & E 30 St,40.741444,-73.975361,259.0,South St & Whitehall St,40.701221,-74.012342,15611,Subscriber,1963,1
2,464,2014-01-01 00:03:59,2014-01-01 00:11:43,228.0,E 48 St & 3 Ave,40.754601,-73.971879,2022.0,E 59 St & Sutton Pl,40.758491,-73.959206,16613,Subscriber,1991,1
3,373,2014-01-01 00:05:15,2014-01-01 00:11:28,519.0,Pershing Square N,40.751884,-73.977702,526.0,E 33 St & 5 Ave,40.747659,-73.984907,15938,Subscriber,1989,1
4,660,2014-01-01 00:05:18,2014-01-01 00:16:18,83.0,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,436.0,Hancock St & Bedford Ave,40.682166,-73.953990,19830,Subscriber,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20551692,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,2
20551693,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,1
20551694,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672816,-73.983524,27746,Subscriber,1935,2
20551695,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,1
20551696,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,0